steps:
- uses: actions/checkout@v2
- uses: eWaterCycle/setup-singularity@v6
  with:
    singularity-version: 3.6.4
- name: Run a singularity container
  run: singularity pull docker://mintproject/swatbasae
